package com.sr.biz.freightbit.core.entity;
// Generated May 10, 2014 12:10:47 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name="contacts"
    ,catalog="freightbit"
)
public class Contacts  implements java.io.Serializable {


     private Integer contactId;
     private int clientId;
     private String referenceTable;
     private int referenceId;
     private String contactType;
     private String firstName;
     private String middleName;
     private String lastName;
     private String phone;
     private String mobile;
     private String fax;
     private String email;
     private Date createdTimestamp;
     private String createdBy;
     private Date modifiedTimestamp;
     private String modifiedBy;

    public Contacts() {
    }

	
    public Contacts(int clientId, String referenceTable, int referenceId, String contactType, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
        this.clientId = clientId;
        this.referenceTable = referenceTable;
        this.referenceId = referenceId;
        this.contactType = contactType;
        this.createdTimestamp = createdTimestamp;
        this.createdBy = createdBy;
        this.modifiedTimestamp = modifiedTimestamp;
        this.modifiedBy = modifiedBy;
    }
    public Contacts(int clientId, String referenceTable, int referenceId, String contactType, String firstName, String middleName, String lastName, String phone, String mobile, String fax, String email, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
       this.clientId = clientId;
       this.referenceTable = referenceTable;
       this.referenceId = referenceId;
       this.contactType = contactType;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.phone = phone;
       this.mobile = mobile;
       this.fax = fax;
       this.email = email;
       this.createdTimestamp = createdTimestamp;
       this.createdBy = createdBy;
       this.modifiedTimestamp = modifiedTimestamp;
       this.modifiedBy = modifiedBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="contactId", unique=true, nullable=false)
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    
    @Column(name="clientId", nullable=false)
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="referenceTable", nullable=false, length=50)
    public String getReferenceTable() {
        return this.referenceTable;
    }
    
    public void setReferenceTable(String referenceTable) {
        this.referenceTable = referenceTable;
    }

    
    @Column(name="referenceId", nullable=false)
    public int getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(int referenceId) {
        this.referenceId = referenceId;
    }

    
    @Column(name="contactType", nullable=false, length=10)
    public String getContactType() {
        return this.contactType;
    }
    
    public void setContactType(String contactType) {
        this.contactType = contactType;
    }

    
    @Column(name="firstName", length=30)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middleName", length=30)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="lastName", length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone", length=30)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="mobile", length=30)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="fax", length=30)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdTimestamp", nullable=false, length=19)
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    
    @Column(name="createdBy", nullable=false, length=10)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifiedTimestamp", nullable=false, length=19)
    public Date getModifiedTimestamp() {
        return this.modifiedTimestamp;
    }
    
    public void setModifiedTimestamp(Date modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    
    @Column(name="modifiedBy", nullable=false, length=10)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


