package com.sr.biz.freightbit.core.entity;
// Generated May 10, 2014 12:10:47 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customeritems generated by hbm2java
 */
@Entity
@Table(name="customeritems"
    ,catalog="freightbit"
)
public class Customeritems  implements java.io.Serializable {


     private Integer customerItemsId;
     private int clientId;
     private int customerId;
     private String itemName;
     private String itemCode;
     private Integer length;
     private Integer width;
     private Integer height;
     private Float srp;
     private Integer criticalQuality;
     private Float basePrice;
     private String note;
     private String description;
     private Date createdTimestamp;
     private String createdBy;
     private Date modifiedTimestamp;
     private String modifiedBy;

    public Customeritems() {
    }

	
    public Customeritems(int clientId, int customerId, String itemCode, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
        this.clientId = clientId;
        this.customerId = customerId;
        this.itemCode = itemCode;
        this.createdTimestamp = createdTimestamp;
        this.createdBy = createdBy;
        this.modifiedTimestamp = modifiedTimestamp;
        this.modifiedBy = modifiedBy;
    }
    public Customeritems(int clientId, int customerId, String itemName, String itemCode, Integer length, Integer width, Integer height, Float srp, Integer criticalQuality, Float basePrice, String note, String description, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
       this.clientId = clientId;
       this.customerId = customerId;
       this.itemName = itemName;
       this.itemCode = itemCode;
       this.length = length;
       this.width = width;
       this.height = height;
       this.srp = srp;
       this.criticalQuality = criticalQuality;
       this.basePrice = basePrice;
       this.note = note;
       this.description = description;
       this.createdTimestamp = createdTimestamp;
       this.createdBy = createdBy;
       this.modifiedTimestamp = modifiedTimestamp;
       this.modifiedBy = modifiedBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customerItemsId", unique=true, nullable=false)
    public Integer getCustomerItemsId() {
        return this.customerItemsId;
    }
    
    public void setCustomerItemsId(Integer customerItemsId) {
        this.customerItemsId = customerItemsId;
    }

    
    @Column(name="clientId", nullable=false)
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="customerId", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="itemName", length=50)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="itemCode", nullable=false, length=10)
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    
    @Column(name="length")
    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }

    
    @Column(name="width")
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }

    
    @Column(name="height")
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }

    
    @Column(name="srp", precision=12, scale=0)
    public Float getSrp() {
        return this.srp;
    }
    
    public void setSrp(Float srp) {
        this.srp = srp;
    }

    
    @Column(name="criticalQuality")
    public Integer getCriticalQuality() {
        return this.criticalQuality;
    }
    
    public void setCriticalQuality(Integer criticalQuality) {
        this.criticalQuality = criticalQuality;
    }

    
    @Column(name="basePrice", precision=12, scale=0)
    public Float getBasePrice() {
        return this.basePrice;
    }
    
    public void setBasePrice(Float basePrice) {
        this.basePrice = basePrice;
    }

    
    @Column(name="note", length=50)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="description", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdTimestamp", nullable=false, length=19)
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    
    @Column(name="createdBy", nullable=false, length=10)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifiedTimestamp", nullable=false, length=19)
    public Date getModifiedTimestamp() {
        return this.modifiedTimestamp;
    }
    
    public void setModifiedTimestamp(Date modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    
    @Column(name="modifiedBy", nullable=false, length=10)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


