package com.sr.biz.freightbit.core.entity;
// Generated May 10, 2014 12:10:47 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
    ,catalog="freightbit"
    , uniqueConstraints = @UniqueConstraint(columnNames="customerCode") 
)
public class Customers  implements java.io.Serializable {


     private Integer customerId;
     private int clientId;
     private String customerCode;
     private String customerName;
     private String customerType;
     private String website;
     private String phone;
     private String mobile;
     private String fax;
     private String email;
     private Boolean dti;
     private Boolean mayorsPermit;
     private Boolean aaf;
     private Boolean signatureCard;
     private Date createdTimestamp;
     private String createdBy;
     private Date modifiedTimestamp;
     private String modifiedBy;

    public Customers() {
    }

	
    public Customers(int clientId, String customerCode, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
        this.clientId = clientId;
        this.customerCode = customerCode;
        this.createdTimestamp = createdTimestamp;
        this.createdBy = createdBy;
        this.modifiedTimestamp = modifiedTimestamp;
        this.modifiedBy = modifiedBy;
    }
    public Customers(int clientId, String customerCode, String customerName, String customerType, String website, String phone, String mobile, String fax, String email, Boolean dti, Boolean mayorsPermit, Boolean aaf, Boolean signatureCard, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
       this.clientId = clientId;
       this.customerCode = customerCode;
       this.customerName = customerName;
       this.customerType = customerType;
       this.website = website;
       this.phone = phone;
       this.mobile = mobile;
       this.fax = fax;
       this.email = email;
       this.dti = dti;
       this.mayorsPermit = mayorsPermit;
       this.aaf = aaf;
       this.signatureCard = signatureCard;
       this.createdTimestamp = createdTimestamp;
       this.createdBy = createdBy;
       this.modifiedTimestamp = modifiedTimestamp;
       this.modifiedBy = modifiedBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customerId", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="clientId", nullable=false)
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="customerCode", unique=true, nullable=false, length=10)
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="customerName", length=50)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="customerType", length=10)
    public String getCustomerType() {
        return this.customerType;
    }
    
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    
    @Column(name="website", length=50)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

    
    @Column(name="phone", length=30)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="mobile", length=30)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="fax", length=30)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="dti")
    public Boolean getDti() {
        return this.dti;
    }
    
    public void setDti(Boolean dti) {
        this.dti = dti;
    }

    
    @Column(name="mayorsPermit")
    public Boolean getMayorsPermit() {
        return this.mayorsPermit;
    }
    
    public void setMayorsPermit(Boolean mayorsPermit) {
        this.mayorsPermit = mayorsPermit;
    }

    
    @Column(name="aaf")
    public Boolean getAaf() {
        return this.aaf;
    }
    
    public void setAaf(Boolean aaf) {
        this.aaf = aaf;
    }

    
    @Column(name="signatureCard")
    public Boolean getSignatureCard() {
        return this.signatureCard;
    }
    
    public void setSignatureCard(Boolean signatureCard) {
        this.signatureCard = signatureCard;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdTimestamp", nullable=false, length=19)
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    
    @Column(name="createdBy", nullable=false, length=10)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifiedTimestamp", nullable=false, length=19)
    public Date getModifiedTimestamp() {
        return this.modifiedTimestamp;
    }
    
    public void setModifiedTimestamp(Date modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    
    @Column(name="modifiedBy", nullable=false, length=10)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


