package com.sr.biz.freightbit.core.entity;

// Generated May 2, 2014 5:40:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupUser generated by hbm2java
 */
@Entity
@Table(name = "group_user", catalog = "freightbit")
public class GroupUser implements java.io.Serializable {

	private long groupUserId;
	private long clientId;
	private long userId;
	private long groupId;

	public GroupUser() {
	}

	public GroupUser(long groupUserId, long clientId, long userId, long groupId) {
		this.groupUserId = groupUserId;
		this.clientId = clientId;
		this.userId = userId;
		this.groupId = groupId;
	}

	@Id
	@Column(name = "groupUserId", unique = true, nullable = false)
	public long getGroupUserId() {
		return this.groupUserId;
	}

	public void setGroupUserId(long groupUserId) {
		this.groupUserId = groupUserId;
	}

	@Column(name = "clientId", nullable = false)
	public long getClientId() {
		return this.clientId;
	}

	public void setClientId(long clientId) {
		this.clientId = clientId;
	}

	@Column(name = "userId", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "groupId", nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

}
